#!/usr/bin/env python

import subprocess, pymongo, math
from datetime import datetime

# program: post-commit
# author: Kevin Chabreck
# description: a git post-commit hook that records commit metadata in a
#			   MongoDB database. 

# fetch the hash and the timestamp from the most recent commit
p = subprocess.Popen(["tail", "-1", ".git/logs/HEAD"], stdout=subprocess.PIPE)
out, err = p.communicate()
hash = out.split(' ')[1]
timestamp = out.split('> ')[1].split(' ')[0]
time = datetime.fromtimestamp(float(timestamp))

# pull insertions, deletions, and # of files edited from the numstat of the commit
p = subprocess.Popen(["git", "diff-tree", "--numstat", hash], stdout=subprocess.PIPE)
out, err = p.communicate()
insertions = deletions = 0
lines = out.split('\n')
for i in range(1, len(lines) - 1):
	line = lines[i].split('\t')
	insertions += int(line[0])
	deletions += int(line[1])
files = len(lines) - 2

# get the hash of each blob in the most recent two commits, and sum
# the size difference from each blob pair to get the total commit size
p = subprocess.Popen(["git", "diff-tree", hash], stdout=subprocess.PIPE)
out, err = p.communicate()
size = 0
lines = out.split('\n')
for i in range(1, len(lines) - 1):
	line = lines[i].split(' ')
	# handle case of new files being tracked
	if int(line[2], 16) == 0:
		sizeA = 0
	else:
		p = subprocess.Popen(["git", "cat-file", "-s", line[2]], stdout=subprocess.PIPE)
		sizeA, err = p.communicate()
	# handle case of files being untracked (removed)
	if int(line[3], 16) == 0:
		sizeB = 0
	else:
		p = subprocess.Popen(["git", "cat-file", "-s", line[3]], stdout=subprocess.PIPE)
		sizeB, err = p.communicate()
	# take the absolute value in case of a negative difference (code/files removed)
	size += math.fabs(int(sizeB) - int(sizeA))

# build the dictionary of commit metadata to be stored in the database
commit = { 	"hash": hash,
			"day": time.weekday(),
			"hour": time.hour,
			"minute": time.minute,
			"insertions": insertions,
			"deletions": deletions,
			"files": files,
			"size": size }

# store the "commit" document in a mongo database
client = pymongo.MongoClient('mongodb://localhost:27017/') #replace with the url of the centralized db
db = client.commitdb #replace 'commitdb' with the name of the centralized db
collection = db.commits #replace 'commits' with the name of a collection in the centralized db
collection.insert(commit)

print commit